name: best_localization
description: "A Flutter localization package with dynamic translations and Kurdish support."
version: 2.0.2
homepage: https://github.com/dosty17/best_localization
repository: https://github.com/dosty17/best_localization
issue_tracker: https://github.com/dosty17/best_localization/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # intl: ^0.20.2
  intl: '>=0.19.0 <0.21.0'
  yaml: '>=3.0.0 <4.0.0'
  xml: '>=6.0.0 <7.0.0'
  http: '>=0.13.0 <2.0.0'
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  verify_translations:

flutter:
