name: best_localization
description: "A Flutter localization package with dynamic translations and Kurdish support."
version: 0.0.4
homepage: https://github.com/dosty17/best_localization
repository: https://github.com/dosty17/best_localization
issue_tracker: https://github.com/dosty17/best_localization/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # intl: ^0.20.2
  intl: '>=0.17.0-0 <0.21.0'
  yaml: ^3.1.2
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
